### PR TITLE
feat: compile as ES Module

### PR DESCRIPTION
**Pull request by boxmein**
### Set package.json `"type": "module"`

* [This opts in all JS files in our library to Node.js ES Module mode](https://nodejs.org/api/packages.html#packagejson-and-file-extensions)
* This allows us to transpile to JavaScript that utilizes Node.js's [ES Modules](https://nodejs.org/api/esm.html#enabling) support

### Set tsconfig.json `"module": "nodenext"`

* Build output will now use `import` and `export` statements, adding new [interoperability considerations](https://nodejs.org/api/esm.html#interoperability-with-commonjs)
* This means you need Node.js 14 or above to import the Javascript API
* This unlocks Webpack tree-shaking optimizations, and removes some webpack optimization warnings in our own code
* [This also adds a requirement to specify every file's file extension in the build output](https://github.com/Qminder/javascript-api/pull/431#issuecomment-1403238833), causing issues for Jest and ESLint

### Configure eslint to operate in `ES Modules` context

* Updated configuration will fix eslint `import` plugin, so that it works after extensions are specified

### Configure Jest to operate in ES Modules mode

* `ts-jest-resolver` will provide proper filename lookup, so that it works after extensions are specified

### Update tests

* `cross-fetch` works better than `isomorphic-fetch` in ES Modules mode, so using that now
* `isomorphic-ws` had no alternative that worked correctly in ES Modules mode... after trying multiple different approaches to work around it, **I opted to only run WebSocket tests on Node.**

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Refactor (Changed implementation, but existing functionality and APIs are not changed)

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [x] All tests related to the changed code pass in development

### Code review 

- [ ] Changes have been reviewed by at least one other engineer

### CODE REVIEW

**Comment by boxmein** [comment]
https://github.com/microsoft/TypeScript/issues/13422#issue-200222154

**Comment by boxmein** [comment]
For "Add .js to the end of the source code's import statements (and configure our editor/linter to enforce it)" we have to switch eslint to eslint-import-resolver-typescript

**Comment by boxmein** [comment]
I also checked if it is possible to go Full ESM -- and use `import` directly in the browser. The answer is "yes, if RxJS and GraphQL add .js extension to their import statements."

[example.html.txt](https://github.com/Qminder/javascript-api/files/10499258/example.html.txt)

**Comment by boxmein** [comment]
Stopped trying to make the subscriptions tests work across two different jest environments.

Explanation here https://github.com/Qminder/javascript-api/pull/431/commits/db4807432c57292ae17b44887c953d9886114cac

**Comment by boxmein** [comment]
# Demonstrating what it does to compilation output

Before this branch:

image


After this branch:

image

**Comment by 2ndalpha** [comment]
@boxmein should se still test on different NodeJS versions? Currently we have test matrix for v12, 14, 15 & 16

**Review by 2ndalpha — APPROVED** [review]
🚀

**Pull request merged**
